use crate::core::types::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Video stream metadata track.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VideoTrack {
    pub stream_id: u32,
    pub stream_order: Option<u32>,
    pub format: VideoCodec,
    pub format_info: Option<String>,
    pub format_profile: Option<String>,
    pub format_level: Option<String>,
    pub format_tier: Option<String>,
    pub format_commercial: Option<String>,
    pub codec_id: Option<String>,
    pub codec_id_info: Option<String>,
    pub duration_ms: Option<f64>,
    pub bit_rate: Option<u64>,
    pub bit_rate_mode: Option<BitrateMode>,
    pub bit_rate_maximum: Option<u64>,
    pub width: u32,
    pub height: u32,
    pub stored_width: Option<u32>,
    pub stored_height: Option<u32>,
    pub sample_aspect_ratio: Option<f64>,
    pub display_aspect_ratio: Option<f64>,
    pub frame_rate_mode: Option<FrameRateMode>,
    pub frame_rate: Option<f64>,
    pub frame_rate_minimum: Option<f64>,
    pub frame_rate_maximum: Option<f64>,
    pub frame_count: Option<u64>,
    pub standard: Option<String>,    // NTSC, PAL, etc.
    pub color_space: Option<String>, // YUV, RGB, etc.
    pub chroma_subsampling: Option<ChromaSubsampling>,
    pub bit_depth: u8,                    // 8, 10, 12, etc.
    pub scan_type: Option<String>,        // Progressive, Interlaced
    pub scan_order: Option<String>,       // TFF, BFF
    pub compression_mode: Option<String>, // Lossy, Lossless
    pub stream_size: Option<u64>,
    pub encoded_library: Option<String>,
    pub encoded_library_name: Option<String>,
    pub encoded_library_version: Option<String>,
    pub encoded_library_settings: Option<String>,
    pub color_range: Option<ColorRange>,
    pub color_primaries: Option<ColorPrimaries>,
    pub transfer_characteristics: Option<TransferCharacteristics>,
    pub matrix_coefficients: Option<MatrixCoefficients>,
    pub mastering_display: Option<MasteringDisplay>,
    pub content_light_level: Option<ContentLightLevel>,
    pub dolby_vision: Option<DolbyVisionInfo>,
    pub hdr_format: Option<String>, // HDR10, HDR10+, Dolby Vision
    pub hdr_format_compatibility: Option<String>,
    pub delay_ms: Option<f64>,
    pub delay_source: Option<String>,
    pub title: Option<String>,
    pub language: Option<String>,
    pub default_flag: bool,
    pub forced_flag: bool,
    pub extra: HashMap<String, String>,
}

impl Default for VideoTrack {
    fn default() -> Self {
        Self {
            stream_id: 1,
            stream_order: None,
            format: VideoCodec::Other("Unknown".to_string()),
            format_info: None,
            format_profile: None,
            format_level: None,
            format_tier: None,
            format_commercial: None,
            codec_id: None,
            codec_id_info: None,
            duration_ms: None,
            bit_rate: None,
            bit_rate_mode: None,
            bit_rate_maximum: None,
            width: 0,
            height: 0,
            stored_width: None,
            stored_height: None,
            sample_aspect_ratio: None,
            display_aspect_ratio: None,
            frame_rate_mode: None,
            frame_rate: None,
            frame_rate_minimum: None,
            frame_rate_maximum: None,
            frame_count: None,
            standard: None,
            color_space: None,
            chroma_subsampling: None,
            bit_depth: 8,
            scan_type: Some("Progressive".to_string()),
            scan_order: None,
            compression_mode: Some("Lossy".to_string()),
            stream_size: None,
            encoded_library: None,
            encoded_library_name: None,
            encoded_library_version: None,
            encoded_library_settings: None,
            color_range: None,
            color_primaries: None,
            transfer_characteristics: None,
            matrix_coefficients: None,
            mastering_display: None,
            content_light_level: None,
            dolby_vision: None,
            hdr_format: None,
            hdr_format_compatibility: None,
            delay_ms: None,
            delay_source: None,
            title: None,
            language: None,
            default_flag: true,
            forced_flag: false,
            extra: HashMap::new(),
        }
    }
}
